"""
FinSight AI — Report Export Service
Export reports to PDF and DOCX formats.
"""

import io
from datetime import datetime

import structlog
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.models.report import Report

logger = structlog.get_logger()


class ReportExportService:
    """Exports financial reports to PDF and DOCX."""

    async def export_pdf(self, report: Report) -> bytes:
        """Generate a professional PDF report."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72,
        )

        styles = getSampleStyleSheet()
        story = []

        # Custom styles
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor("#0F172A"),
        )
        section_style = ParagraphStyle(
            "SectionTitle",
            parent=styles["Heading2"],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=20,
            textColor=colors.HexColor("#1E40AF"),
        )
        body_style = ParagraphStyle(
            "BodyText",
            parent=styles["Normal"],
            fontSize=11,
            spaceAfter=8,
            leading=16,
        )

        # Title
        story.append(Paragraph(report.title, title_style))
        story.append(Paragraph(
            f"Generated: {report.created_at.strftime('%B %d, %Y')} | "
            f"Type: {report.report_type.value.replace('_', ' ').title()}",
            body_style,
        ))
        story.append(Spacer(1, 20))

        # Sections
        sections = [
            ("Executive Summary", report.executive_summary),
            ("Key Findings", report.key_findings),
            ("Detailed Analysis", report.detailed_analysis),
            ("Opportunities", report.opportunities),
            ("Risks", report.risks),
            ("Regulatory Impact", report.regulatory_impact),
            ("Recommendation", report.recommendation),
        ]

        for section_title, content in sections:
            if content:
                story.append(Paragraph(section_title, section_style))
                # Split by paragraphs
                for para in content.split("\n"):
                    if para.strip():
                        story.append(Paragraph(para.strip(), body_style))
                story.append(Spacer(1, 10))

        # Citations
        if report.citations:
            story.append(Paragraph("Sources & Citations", section_style))
            for i, citation in enumerate(report.citations, 1):
                source = citation.get("source", "Unknown")
                page = citation.get("page", "")
                citation_text = f"[{i}] {source}"
                if page:
                    citation_text += f", Page {page}"
                story.append(Paragraph(citation_text, body_style))

        # Footer
        story.append(Spacer(1, 30))
        story.append(Paragraph(
            "Generated by FinSight AI — Agentic Financial Intelligence Platform",
            ParagraphStyle("Footer", parent=body_style, fontSize=9, textColor=colors.grey),
        ))

        doc.build(story)
        return buffer.getvalue()

    async def export_docx(self, report: Report) -> bytes:
        """Generate a professional DOCX report."""
        doc = DocxDocument()

        # Title
        title = doc.add_heading(report.title, level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in title.runs:
            run.font.color.rgb = RGBColor(15, 23, 42)

        # Metadata
        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta_run = meta.add_run(
            f"Generated: {report.created_at.strftime('%B %d, %Y')} | "
            f"Type: {report.report_type.value.replace('_', ' ').title()}"
        )
        meta_run.font.size = Pt(10)
        meta_run.font.color.rgb = RGBColor(100, 116, 139)

        doc.add_paragraph()  # Spacer

        # Sections
        sections = [
            ("Executive Summary", report.executive_summary),
            ("Key Findings", report.key_findings),
            ("Detailed Analysis", report.detailed_analysis),
            ("Opportunities", report.opportunities),
            ("Risks", report.risks),
            ("Regulatory Impact", report.regulatory_impact),
            ("Recommendation", report.recommendation),
        ]

        for section_title, content in sections:
            if content:
                heading = doc.add_heading(section_title, level=1)
                for run in heading.runs:
                    run.font.color.rgb = RGBColor(30, 64, 175)

                for para_text in content.split("\n"):
                    if para_text.strip():
                        p = doc.add_paragraph(para_text.strip())
                        for run in p.runs:
                            run.font.size = Pt(11)

        # Citations
        if report.citations:
            doc.add_heading("Sources & Citations", level=1)
            for i, citation in enumerate(report.citations, 1):
                source = citation.get("source", "Unknown")
                page = citation.get("page", "")
                text = f"[{i}] {source}"
                if page:
                    text += f", Page {page}"
                doc.add_paragraph(text)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer_run = footer.add_run(
            "Generated by FinSight AI — Agentic Financial Intelligence Platform"
        )
        footer_run.font.size = Pt(8)
        footer_run.font.color.rgb = RGBColor(148, 163, 184)

        buffer = io.BytesIO()
        doc.save(buffer)
        return buffer.getvalue()
